### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by jamesbraza** [suzuki-shunsuke/github-action-renovate-config-validator#786]
With v1.1.1, I am getting a lot of `npm warn`s:

```none
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
```

Do you mind resolving these, to clean up CI logs?

---

Here is my GitHub Action set up:

```yaml
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
```
